"use client";

import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import SvgLogin from "@/app/icons/SvgLogin";
import SvgLogout from "@/app/icons/SvgLogout";
import SvgAccountCircle from "../icons/SvgAccountCircle";
import { useEffect, useState } from "react";
import { onAuthStateChanged, signOut, User } from "firebase/auth";
import { auth } from "@/app/lib/firebase";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Header() {
  const [user, setUser] = useState<User | null>(null);
  const [menuOpen, setMenuOpen] = useState(false);

  const handleLogout = async () => {
    await signOut(auth);
  };

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      setUser(user);
    });

    return () => unsubscribe();
  }, []);
  return (
    <div>
      <header className="app-bar">
        <Image src="/logo.svg" alt="Logo" width={48} height={48} />
        <div className="title-area">
          <h1 className="title">いよ管</h1>
        </div>
        <div style={{ flexGrow: 1 }}></div>
        {user ? (
          <button onClick={() => setMenuOpen(!menuOpen)}>
            <SvgAccountCircle />
          </button>
        ) : (
          <Link href="/login">
            <SvgLogin />
          </Link>
        )}
      </header>
      <div
        className={`menu ${menuOpen ? "" : "hidden"}`}
        onClick={() => setMenuOpen(false)}
        style={{
          width: "12rem",
          position: "absolute",
          right: "0.5rem",
          top: "3.5rem",
        }}
      >
        <button onClick={handleLogout}>
          <span className="prefix">
            <SvgLogout />
          </span>
          Logout
        </button>
      </div>
    </div>
  );
}
