export interface BlueskyConfig {
  service: string; // Manually set on UI
  identifier: string; // Manually set on UI
  password: string; // Manually set on UI
}

export interface MastodonConfig {
  token: string; // Manually set on UI
  url: string; // Manually set on UI
}

export interface MisskeyConfig {
  token: string; // Manually set on UI
  url: string; // Manually set on UI
}

export interface TwitterConfig {
  redirect_uri: string; // Manually set on UI
  client_id: string; // Manually set on UI
  client_secret: string; // Manually set on UI
  code_verifier: string; // challenge code generated on UI
  code?: string; // generated by OAuth flow
  access_token?: string; // generated by OAuth flow
  refresh_token?: string; // generated by OAuth flow
  expires_in?: number; // generated by OAuth flow
}

export interface ThreadsConfig {
  redirect_uri: string; // Manually set on UI
  client_id: string; // Manually set on UI
  client_secret: string; // Manually set on UI
  code?: string; // generated by OAuth flow
  access_token?: string; // generated by OAuth flow
  user_id?: string; // generated by OAuth flow
  expires_in?: number; // generated by OAuth flow
}

export interface InstagramConfig {
  client_id: string; // Manually set on UI
  access_token: string; // Manually set on UI
  expires_in?: number; // generated by OAuth flow
}

export interface TumblrConfig {
  redirect_uri: string; // Manually set on UI
  client_id: string; // Manually set on UI
  client_secret: string; // Manually set on UI
  code?: string; // generated by OAuth flow
  access_token?: string; // generated by OAuth flow
  refresh_token?: string; // generated by OAuth flow
  expires_in?: number; // generated by OAuth flow
}

export interface WordPressConfig {
  service: string; // Manually set on UI
  identifier: string; // Manually set on UI
  password: string; // Manually set on UI
  category: string; // Manually set on UI
}
